# Generated by Django 6.0.5 on 2026-06-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_backfill_instructor_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
