# Generated by Django 6.0.5 on 2026-06-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_exam', '0004_examattempt_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='passing_marks',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
