# Generated by Django 6.0.5 on 2026-06-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_exam', '0005_exam_passing_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
